gpu.mode: hybrid

paper.isEnabled: false
paper.mode: Sky

shader.isEnabled: false
shader.mode: vibrance

interface.performance = true
interface.scheme: van

touchpad.isEnabled: true

screenpad.enabledSetup: DP-1, 2880x864@120, 0x900, 2, bitdepth, 10
screenpad.enabledSetup.scaled: DP-1, 2880x864, 0x600, 3, bitdepth, 10
screenpad.disabledSetup: DP-1, disabled
screenpad.isEnabled: true

screen.enabledSetup: eDP-1, 2880x1800@120, 0x0, 2, bitdepth, 10
screen.enabledSetup.scaled: eDP-1, 2880x1800@120, 0x0, 3, bitdepth, 10
screen.disabledSetup: eDP-1, disabled
screen.isEnabled: true

brightness.intel_backlight: 360
brightness.asus_screenpad: 211
brightness.asus::kbd_backlight: 1
brightness.phy0-led: 1
brightness.input3::numlock: 0
brightness.input3::capslock: 0
brightness.input3::scrolllock: 0
brightness.platform::micmute: 1
