bind = SUPER, q, killactive
bind = SUPER SHIFT, X, exec, hyprctl activewindow | grep pid | tr -d 'pid:' | xargs kill 

bind = CTRL, TAB, exec, pkill waybar || waybar
bind = SUPER, TAB, exec, pkill tofi-drun || tofi-drun --drun-launch=true && hyprctl dispatch submap

bindl = , XF86TouchpadToggle, exec, herodot touchad set toggle
bindl = SUPER, XF86TouchpadToggle, exec,  herodot screenpad set state toggle

bind = SUPER CTRL ALT, M, exec, herodot scheme set mode next
bind = SUPER CTRL ALT, N, exec, herodot wifi set state toggle
bind = SUPER CTRL ALT, B, exec, herodot bluetooth set state toggle
bind = SUPER CTRL ALT, V, exec, herodot idle set state toggle

bind = SUPER, L, exec, herodot shutdown lock

bind = CTRL ALT, BACKSPACE, exec, herodot shutdown exit
bind = CTRL ALT, DELETE, exec, herodot shutdown reboot
bind = , XF86PowerOff, exec, herodot shutdown poweroff

bind = SUPER SHIFT, C, exec, kitty --class clipse -e clipse

bind = SUPER, C, sendshortcut, SHIFT CTRL, C, %kitt.*$
bind = SUPER, V, sendshortcut, SHIFT CTRL, V, %kitt.*$
