bindel = , XF86MonBrightnessUp, exec, herodot brightness all set level increase 
bindel = , XF86MonBrightnessDown, exec, herodot brightness all set level decrease

bindel = ALT, XF86MonBrightnessUp, exec, herodot brightness all set level up
bindel = ALT, XF86MonBrightnessDown, exec, herodot brightness all set level down

bindel = SHIFT, XF86MonBrightnessUp, exec, herodot brightness all set level max
bindel = SHIFT, XF86MonBrightnessDown, exec, herodot brightness all set level min


