bindel = , XF86MonBrightnessUp, exec, herodot brightness all set increase 
bindel = , XF86MonBrightnessDown, exec, herodot brightness all set decrease

bindel = ALT, XF86MonBrightnessUp, exec, herodot brightness all set up
bindel = ALT, XF86MonBrightnessDown, exec, herodot brightness all set down

bindel = SHIFT, XF86MonBrightnessUp, exec, herodot brightness all set max
bindel = SHIFT, XF86MonBrightnessDown, exec, herodot brightness all set min


