bind = SUPER SHIFT, G, togglegroup

bind = SUPER SHIFT, B, exec, changegroupactive b
bind = SUPER SHIFT, N, exec, changegroupactive f

bind = SUPER SHIFT, left, exec, movewindoworgroup l
bind = SUPER SHIFT, right, exec, movewindoworgroup r
bind = SUPER SHIFT, up, exec, movewindoworgroup u
bind = SUPER SHIFT, down, exec, movewindoworgroup d

