bind = SHIFT CTRL ALT, S, exec, herodot shader set status off save

bind = CTRL ALT, S, exec, herodot shader set status on; herodot submap timeout 3 herodot shader set restore
bind = CTRL ALT, S, submap, shader

submap = shader

bind = , right, exec, herodot shader set mode next; herodot submap timeout 3 herodot shader set restore
bind = , left, exec, herodot shader set mode back; herodot submap timeout 3 herodot shader set restore

bind = , escape, exec, herodot shader set restore
bind = , escape, submap, reset

bind = , return, exec, herodot shader set mode $(herodot shader get mode) save
bind = , return, exec, :; waynot send "Shader" "$(herodot shader get mode) selected"
bind = , return, submap, reset

bind = SHIFT CTRL ALT, S, exec, herodot shader set status off save
bind = SHIFT CTRL ALT, S, submap, reset

submap = reset
