#!/bin/sh

usage() {
    cat << EOF
Usage:  herodot gpu get mode
        herodot gpu set mode integrated|hybrid
EOF
    exit 1
}

get_mode() {
    echo $(envycontrol -q)
}

get_temperature() {
    echo "$(nvidia-smi --query-gpu=temperature.gpu --format=csv,noheader)"
}

set_mode() {
    local mode="$1"
    if zenity --question \
              --icon="/usr/share/icons/empty.png" \
              --text="Are you sure you want to toggle GPU to $mode? It require reboot."; then
        pkexec envycontrol -s "$mode"
        pkexec mkinitcpio -P
        if [ "$mode" = "integrated" ]; then
            find "$HOME/.config" -type f -exec sed -i 's/eDP-2/eDP-1/g' {} \;
        else
            find "$HOME/.config" -type f -exec sed -i 's/eDP-1/eDP-2/g' {} \;
        fi
    fi
}

toggle() {
    [ $(get_mode) = "integrated" ] && set_mode "hybrid" || set_mode "integrated"
}

case "$1" in
    "get")
        case "$2" in
            "mode")
                get_mode
                ;;
            "temperature")
                get_temperature
                ;;
            *)
                usage
                ;;
        esac
        ;;
    "set")
        case "$2" in
            "mode")
                case "$3" in
                    "integrated")
                        set_mode "integrated"                
                        ;;
                    "hybrid")
                        set_mode "hybrid"
                        ;;
                    "toggle")
                        toggle
                        ;;
                    *)
                        usage
                        ;;
                esac
            ;;
            *)
                usage
                ;;
        esac
        ;;
    *)
        usage
        ;;
esac
