#!/bin/sh

usage() {
    cat << EOF
Usage:  herodot keyboard get mode
        herodot keyboard set next
EOF
}

DEVICE="at-translated-set-2-keyboard"

get_mode() {
    echo "$(hyprctl devices -j | jq -r --arg device "$DEVICE" ".keyboards[] | select(.name == \$device) | .active_keymap")"
}

set_next() {
    hyprctl switchxkblayout "$DEVICE" next
}

case "$1" in
    "get")
        case "$2" in
            "mode")
                get_mode
                ;;
            *)
                usage
                ;;
        esac
        ;;
    "set")
        case "$2" in
            "next")
                set_next
                ;;
            *)
                usage
                ;;
        esac
        ;;
    *)
        usage
        ;;
esac
